export const SHOW_SUCCESS_NOTIFICATION: "notification/SHOW_SUCCESS_NOTIFICATION" =
  "notification/SHOW_SUCCESS_NOTIFICATION";
export const HIDE_SUCCESS_NOTIFICATION: "notification/HIDE_SUCCESS_NOTIFICATION" =
    "notification/HIDE_SUCCESS_NOTIFICATION";
export const SHOW_WARNING_NOTIFICATION: "notification/SHOW_WARNING_NOTIFICATION" =
  "notification/SHOW_WARNING_NOTIFICATION";
export const HIDE_WARNING_NOTIFICATION: "notification/HIDE_WARNING_NOTIFICATION" =
    "notification/HIDE_WARNING_NOTIFICATION";
export const SHOW_ERROR_NOTIFICATION: "notification/SHOW_ERROR_NOTIFICATION" =
    "notification/SHOW_ERROR_NOTIFICATION";
export const HIDE_ERROR_NOTIFICATION: "notification/HIDE_ERROR_NOTIFICATION" =
    "notification/HIDE_ERROR_NOTIFICATION";
