// Customer Logging In
export const AUTHENTICATED_REQUEST: "customer/AUTHENTICATED_REQUEST" =
  "customer/AUTHENTICATED_REQUEST";
export const AUTHENTICATED_SUCCESS: "customer/AUTHENTICATED_SUCCESS" =
  "customer/AUTHENTICATED_SUCCESS";
export const AUTHENTICATED_FAILURE: "customer/AUTHENTICATED_FAILURE" =
  "customer/AUTHENTICATED_FAILURE";

// Customer Logging out
export const UNAUTHENTICATED_REQUEST: "customer/UNAUTHENTICATED_REQUEST" =
  "customer/UNAUTHENTICATED_REQUEST";
export const UNAUTHENTICATED_SUCCESS: "customer/UNAUTHENTICATED_SUCCESS" =
  "customer/UNAUTHENTICATED_SUCCESS";
export const UNAUTHENTICATED_FAILURE: "customer/UNAUTHENTICATED_FAILURE" =
  "customer/UNAUTHENTICATED_FAILURE";

// Customer Access Token CREATE
export const ACCESS_TOKEN_CREATE_REQUEST: "customer/ACCESS_TOKEN_CREATE_REQUEST" =
  "customer/ACCESS_TOKEN_CREATE_REQUEST";
export const ACCESS_TOKEN_CREATE_SUCCESS: "customer/ACCESS_TOKEN_CREATE_SUCCESS" =
  "customer/ACCESS_TOKEN_CREATE_SUCCESS";
export const ACCESS_TOKEN_CREATE_FAILURE: "customer/ACCESS_TOKEN_CREATE_FAILURE" =
  "customer/ACCESS_TOKEN_CREATE_FAILURE";

// Customer Access Token DELETE
export const ACCESS_TOKEN_DELETE_REQUEST: "customer/ACCESS_TOKEN_DELETE_REQUEST" =
  "customer/ACCESS_TOKEN_DELETE_REQUEST";
export const ACCESS_TOKEN_DELETE_SUCCESS: "customer/ACCESS_TOKEN_DELETE_SUCCESS" =
  "customer/ACCESS_TOKEN_DELETE_SUCCESS";
export const ACCESS_TOKEN_DELETE_FAILURE: "customer/ACCESS_TOKEN_DELETE_FAILURE" =
  "customer/ACCESS_TOKEN_DELETE_FAILURE";

// Customer Access Token READ
export const ACCESS_TOKEN_READ: "customer/ACCESS_TOKEN_READ" =
  "customer/ACCESS_TOKEN_READ";

// Customer Access Token UPDATE
export const ACCESS_TOKEN_UPDATE: "customer/ACCESS_TOKEN_UPDATE" =
  "customer/ACCESS_TOKEN_UPDATE";

// Customer Expiry Token CREATE
export const EXPIRY_TOKEN_CREATE_REQUEST: "customer/EXPIRY_TOKEN_CREATE_REQUEST" =
  "customer/EXPIRY_TOKEN_CREATE_REQUEST";
export const EXPIRY_TOKEN_CREATE_SUCCESS: "customer/EXPIRY_TOKEN_CREATE_SUCCESS" =
  "customer/EXPIRY_TOKEN_CREATE_SUCCESS";
export const EXPIRY_TOKEN_CREATE_FAILURE: "customer/EXPIRY_TOKEN_CREATE_FAILURE" =
  "customer/EXPIRY_TOKEN_CREATE_FAILURE";

// Customer Expiry Token DELETE
export const EXPIRY_TOKEN_DELETE_REQUEST: "customer/EXPIRY_TOKEN_DELETE_REQUEST" =
  "customer/EXPIRY_TOKEN_DELETE_REQUEST";
export const EXPIRY_TOKEN_DELETE_SUCCESS: "customer/EXPIRY_TOKEN_DELETE_SUCCESS" =
  "customer/EXPIRY_TOKEN_DELETE_SUCCESS";
export const EXPIRY_TOKEN_DELETE_FAILURE: "customer/EXPIRY_TOKEN_DELETE_FAILURE" =
  "customer/EXPIRY_TOKEN_DELETE_FAILURE";

// Customer Expiry Token READ
export const EXPIRY_TOKEN_READ: "customer/EXPIRY_TOKEN_READ" =
  "customer/EXPIRY_TOKEN_READ";

// Customer Expiry Token VALIDATE
export const EXPIRY_TOKEN_VALIDATE: "customer/EXPIRY_TOKEN_VALIDATE" =
  "customer/EXPIRY_TOKEN_VALIDATE";

// Customer Expiry Token UPDATE
export const EXPIRY_TOKEN_UPDATE: "customer/EXPIRY_TOKEN_UPDATE" =
  "customer/EXPIRY_TOKEN_UPDATE";

// Customer Destroy
export const CUSTOMER_DESTROY_REQUEST: "customer/CUSTOMER_DESTROY_REQUEST" =
  "customer/CUSTOMER_DESTROY_REQUEST";
export const CUSTOMER_DESTROY_SUCCESS: "customer/CUSTOMER_DESTROY_SUCCESS" =
  "customer/CUSTOMER_DESTROY_SUCCESS";
export const CUSTOMER_DESTROY_FAILURE: "customer/CUSTOMER_DESTROY_FAILURE" =
  "customer/CUSTOMER_DESTROY_FAILURE";
